# Setup
title: "Taiyi's note"
description: ''
url: 'https://moved0311.github.io'
baseurl: '/'

author:
  name: 'Taiyi'
  email: moved0311@gmail.com
  facebook_username: 100000329876068
  github_username:  moved0311



# Dependencies
markdown: kramdown
# markdown: redcarpet
highlighter: rouge
gems: [jekyll-paginate, jekyll-gist]

# article settings
destination: _site
paginate: 10
permalink: /:year/:title/
kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false
